package com.asu.model;

/**
 * Report Class
 * Demonstrates: Encapsulation, Data Abstraction, Report Generation Pattern
 *
 * The Report class handles:
 * - Report creation and management
 * - Report type categorization
 * - Report generation with data
 * - Report formatting and display
 */
public class report {

    // Private attributes - Demonstrates Encapsulation
    private String reportId;
    private String reportType;       // Sales, Service, Performance, Financial
    private String generatedDate;
    private String generatedBy;      // Manager who generated it
    private String period;           // Time period (Monthly, Quarterly, Annual)
    private String status;           // Draft, Completed, Archived
    private StringBuilder reportContent;

    /**
     * Constructor - Initialize Report with required details
     * @param reportId Unique report identifier
     * @param reportType Type of report (Sales, Service, Performance, Financial)
     * @param generatedBy Manager who generated the report
     * @param period Time period for the report
     */
    public report(String reportId, String reportType, String generatedBy, String period) {
        this.reportId = reportId;
        this.reportType = reportType;
        this.generatedBy = generatedBy;
        this.period = period;
        this.generatedDate = "[System Date]";
        this.status = "Draft";
        this.reportContent = new StringBuilder();
    }

    // ============== GETTER METHODS ==============
    public String getReportId() {
        return reportId;
    }

    public String getReportType() {
        return reportType;
    }

    public String getGeneratedDate() {
        return generatedDate;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    public String getPeriod() {
        return period;
    }

    public String getStatus() {
        return status;
    }

    public String getReportContent() {
        return reportContent.toString();
    }

    // ============== SETTER METHODS ==============
    public void setReportType(String reportType) {
        if (reportType != null && !reportType.isEmpty()) {
            if (isValidReportType(reportType)) {
                this.reportType = reportType;
            } else {
                System.out.println("Error: Invalid report type. Must be Sales, Service, Performance, or Financial");
            }
        }
    }

    public void setPeriod(String period) {
        if (period != null && !period.isEmpty()) {
            this.period = period;
        }
    }

    public void setStatus(String status) {
        if (status != null && !status.isEmpty()) {
            if (status.equalsIgnoreCase("Draft") || status.equalsIgnoreCase("Completed") ||
                    status.equalsIgnoreCase("Archived")) {
                this.status = status;
            } else {
                System.out.println("Error: Invalid status. Must be Draft, Completed, or Archived");
            }
        }
    }

    // ============== REPORT GENERATION METHODS ==============

    /**
     * Generate a sales report
     * Demonstrates: Complex report generation with data compilation
     *
     * @return true if report generated successfully
     */
    public boolean generateSalesReport() {
        if (!reportType.equalsIgnoreCase("Sales")) {
            System.out.println("Error: This method is for Sales reports only");
            return false;
        }

        reportContent.setLength(0); // Clear previous content

        reportContent.append("╔════════════════════════════════════════════════╗\n");
        reportContent.append("║              SALES REPORT                      ║\n");
        reportContent.append("╚════════════════════════════════════════════════╝\n\n");

        reportContent.append("Report ID: ").append(reportId).append("\n");
        reportContent.append("Generated Date: ").append(generatedDate).append("\n");
        reportContent.append("Generated By: ").append(generatedBy).append("\n");
        reportContent.append("Period: ").append(period).append("\n\n");

        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("SALES SUMMARY\n");
        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("[Sales data compiled from appointment and payment records]\n");
        reportContent.append("Total Appointments: [Retrieved from database]\n");
        reportContent.append("Total Revenue: [Calculated from payments]\n");
        reportContent.append("Average Transaction: [Calculated]\n");
        reportContent.append("Top Services: [Analyzed]\n\n");

        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("KEY METRICS\n");
        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("Normal Services: [Count]\n");
        reportContent.append("Major Services: [Count]\n");
        reportContent.append("Customer Satisfaction: [Rating]\n\n");

        this.status = "Completed";
        System.out.println("✓ Sales report generated successfully");
        return true;
    }

    /**
     * Generate a service performance report
     * Demonstrates: Performance metrics compilation
     *
     * @return true if report generated successfully
     */
    public boolean generateServiceReport() {
        if (!reportType.equalsIgnoreCase("Service")) {
            System.out.println("Error: This method is for Service reports only");
            return false;
        }

        reportContent.setLength(0);

        reportContent.append("╔════════════════════════════════════════════════╗\n");
        reportContent.append("║         SERVICE PERFORMANCE REPORT             ║\n");
        reportContent.append("╚════════════════════════════════════════════════╝\n\n");

        reportContent.append("Report ID: ").append(reportId).append("\n");
        reportContent.append("Generated Date: ").append(generatedDate).append("\n");
        reportContent.append("Generated By: ").append(generatedBy).append("\n");
        reportContent.append("Period: ").append(period).append("\n\n");

        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("TECHNICIAN PERFORMANCE\n");
        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("[Technician statistics retrieved from database]\n");
        reportContent.append("Total Appointments Completed: [Count]\n");
        reportContent.append("Average Completion Time: [Calculated]\n");
        reportContent.append("Customer Ratings: [Analyzed]\n");
        reportContent.append("Top Performing Technician: [Identified]\n\n");

        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("SERVICE QUALITY METRICS\n");
        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("On-Time Completion Rate: [Calculated]%\n");
        reportContent.append("Customer Satisfaction Rate: [Calculated]%\n");
        reportContent.append("Service Repeat Rate: [Calculated]%\n\n");

        this.status = "Completed";
        System.out.println("✓ Service report generated successfully");
        return true;
    }

    /**
     * Generate a financial report
     * Demonstrates: Financial data analysis
     *
     * @return true if report generated successfully
     */
    public boolean generateFinancialReport() {
        if (!reportType.equalsIgnoreCase("Financial")) {
            System.out.println("Error: This method is for Financial reports only");
            return false;
        }

        reportContent.setLength(0);

        reportContent.append("╔════════════════════════════════════════════════╗\n");
        reportContent.append("║         FINANCIAL ANALYSIS REPORT              ║\n");
        reportContent.append("╚════════════════════════════════════════════════╝\n\n");

        reportContent.append("Report ID: ").append(reportId).append("\n");
        reportContent.append("Generated Date: ").append(generatedDate).append("\n");
        reportContent.append("Generated By: ").append(generatedBy).append("\n");
        reportContent.append("Period: ").append(period).append("\n\n");

        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("REVENUE ANALYSIS\n");
        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("Total Revenue: RM [Calculated]\n");
        reportContent.append("Revenue by Service Type:\n");
        reportContent.append("  - Normal Services: RM [Calculated]\n");
        reportContent.append("  - Major Services: RM [Calculated]\n");
        reportContent.append("Average Revenue per Appointment: RM [Calculated]\n\n");

        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("PAYMENT ANALYSIS\n");
        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("Total Payments Collected: [Count]\n");
        reportContent.append("Payment Methods:\n");
        reportContent.append("  - Cash: [Count & Amount]\n");
        reportContent.append("  - Card: [Count & Amount]\n");
        reportContent.append("  - Cheque: [Count & Amount]\n\n");

        this.status = "Completed";
        System.out.println("✓ Financial report generated successfully");
        return true;
    }

    /**
     * Generate a performance report
     * Demonstrates: Multi-factor analysis
     *
     * @return true if report generated successfully
     */
    public boolean generatePerformanceReport() {
        if (!reportType.equalsIgnoreCase("Performance")) {
            System.out.println("Error: This method is for Performance reports only");
            return false;
        }

        reportContent.setLength(0);

        reportContent.append("╔════════════════════════════════════════════════╗\n");
        reportContent.append("║       OVERALL PERFORMANCE REPORT               ║\n");
        reportContent.append("╚════════════════════════════════════════════════╝\n\n");

        reportContent.append("Report ID: ").append(reportId).append("\n");
        reportContent.append("Generated Date: ").append(generatedDate).append("\n");
        reportContent.append("Generated By: ").append(generatedBy).append("\n");
        reportContent.append("Period: ").append(period).append("\n\n");

        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("EXECUTIVE SUMMARY\n");
        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("Total Appointments: [Count]\n");
        reportContent.append("Completion Rate: [Percentage]%\n");
        reportContent.append("Customer Satisfaction: [Average Rating]/5.0\n");
        reportContent.append("Revenue Growth: [Percentage]%\n\n");

        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("STAFF PERFORMANCE\n");
        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("[Individual and team performance metrics]\n\n");

        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("RECOMMENDATIONS\n");
        reportContent.append("════════════════════════════════════════════════\n");
        reportContent.append("[Analysis-based recommendations for improvement]\n\n");

        this.status = "Completed";
        System.out.println("✓ Performance report generated successfully");
        return true;
    }

    // ============== REPORT MANAGEMENT METHODS ==============

    /**
     * Display the generated report
     * Demonstrates: Report presentation
     */
    public void displayReport() {
        if (reportContent.length() == 0) {
            System.out.println("Error: Report has not been generated yet. Please generate the report first.");
            return;
        }

        System.out.println(reportContent.toString());
    }

    /**
     * Export report as text
     * Demonstrates: Report export functionality
     *
     * @return report as formatted string
     */
    public String exportReport() {
        if (reportContent.length() == 0) {
            System.out.println("Error: Report has not been generated yet");
            return "";
        }

        return reportContent.toString();
    }

    /**
     * Archive the report
     * Demonstrates: Report lifecycle management
     *
     * @return true if archived successfully
     */
    public boolean archiveReport() {
        if (status.equalsIgnoreCase("Archived")) {
            System.out.println("Report is already archived");
            return false;
        }

        this.status = "Archived";
        System.out.println("✓ Report archived successfully (ID: " + reportId + ")");
        return true;
    }

    // ============== UTILITY METHODS ==============

    /**
     * Validate report type
     */
    private boolean isValidReportType(String type) {
        return type.equalsIgnoreCase("Sales") ||
                type.equalsIgnoreCase("Service") ||
                type.equalsIgnoreCase("Performance") ||
                type.equalsIgnoreCase("Financial");
    }

    /**
     * Get report summary
     * Demonstrates: Summary generation
     */
    public String getReportSummary() {
        return "Report ID: " + reportId +
                ", Type: " + reportType +
                ", Period: " + period +
                ", Status: " + status;
    }

    /**
     * Convert report object to string format for file storage
     * Format: reportId|reportType|generatedDate|generatedBy|period|status
     */
    @Override
    public String toString() {
        return reportId + "|" + reportType + "|" + generatedDate + "|" + generatedBy + "|" + period + "|" + status;
    }

    /**
     * Display report metadata
     */
    public void displayReportMetadata() {
        System.out.println("\n════════════════════════════════════════════════");
        System.out.println("   REPORT METADATA");
        System.out.println("════════════════════════════════════════════════");
        System.out.println("Report ID: " + reportId);
        System.out.println("Report Type: " + reportType);
        System.out.println("Generated Date: " + generatedDate);
        System.out.println("Generated By: " + generatedBy);
        System.out.println("Period: " + period);
        System.out.println("Status: " + status);
        System.out.println("Content Size: " + reportContent.length() + " bytes");
        System.out.println("════════════════════════════════════════════════\n");
    }
}
